@sourceId = 9d80ca1b-b428-4ead-8b00-4125207e8966
@actionId = e74ab282-6130-4edb-ac7b-fbaf24f48939

### CREATE ACTION
# @no-log
POST {{backend}}/action
Content-Type: application/json

{
  "name": "test2",
  "sourceId": "{{sourceId}}"
}

###

### LIST ACTIONS (current user)
# @no-log
GET {{backend}}/action
    ?pageNumber=1
    &perPage=100
    &orderBy=createdAt
    &sortOrder=ASC
Content-Type: application/json

###

### GET ACTION BY ID
# @no-log
GET {{backend}}/action/{{actionId}}
Content-Type: application/json

###

### UPDATE ACTION
# @no-log
PATCH {{backend}}/action/{{actionId}}
Content-Type: application/json

{
  "name": "signup"
}

###

### DELETE ACTION
# @no-log
DELETE {{backend}}/action/{{actionId}}
Content-Type: application/json

###
