@sourceId = e28e9c92-6366-40de-9569-3cec0caa6549
@actionId = 0f72eab0-24f3-488b-a83d-44201b3d2b37

### CREATE ACTION
# @no-log
POST {{backend}}/action
Content-Type: application/json

{
  "name": "signup",
  "sourceId": "{{sourceId}}"
}

###

### LIST ACTIONS (current user)
# @no-log
GET {{backend}}/action
Content-Type: application/json

###

### GET ACTION BY ID
# @no-log
GET {{backend}}/action/{{actionId}}
Content-Type: application/json

###

### UPDATE ACTION
# @no-log
PATCH {{backend}}/action/{{actionId}}
Content-Type: application/json

{
  "name": "signup"
}

###

### DELETE ACTION
# @no-log
DELETE {{backend}}/action/{{actionId}}
Content-Type: application/json

###
