### LOGIN
# @no-log
POST {{backend}}/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

### LOGOUT
# @no-log
GET {{backend}}/auth/logout
Content-Type: application/json

###

### SIGN UP
# @no-log
POST {{backend}}/auth/signup
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "email": "onalee_caldera6ctm@assigned.pyg"
}

###
