@actionId = 69099440-dccd-407f-a397-c6b037efbf01
@publicId = 319c52bf-c3e0-4549-bc78-d4640d428d03
@eventId = 908d82b0-bedd-4b04-8172-5200396cd92d

### CREATE EVENT
# @no-log
POST {{backend}}/event
Content-Type: application/json

{
  "localTime": "2025-01-01T12:00:00.000Z",
  "ip": "127.0.0.1",
  "data": { "page": "/home", "clicked": true },
  "actionId": "{{actionId}}"
}

###

### LIST EVENTS (current user)
# @no-log
GET {{backend}}/event
    ?pageNumber=1
    &perPage=5
    &orderBy=createdAt
    &sortOrder=DESC
    &actionId={{actionId}}
Content-Type: application/json

###

### GET EVENT BY ID
# @no-log
GET {{backend}}/event/{{eventId}}
Content-Type: application/json

###

### UPDATE EVENT
# @no-log
PATCH {{backend}}/event/{{eventId}}
Content-Type: application/json

{
  "ip": "192.168.1.10",
  "data": { "page": "/dashboard", "clicked": false }
}

###

### DELETE EVENT
# @no-log
DELETE {{backend}}/event/{{eventId}}
Content-Type: application/json

###

### PUBLIC EVENT
POST {{backend}}/public
Content-Type: application/json

{
  "id": "{{publicId}}",
  "data": { "page": "/home", "clicked": true },
  "ip": "127.0.0.1",
  "localTime": "2025-09-12T08:28:09.163Z"
}

###
