@actionId = 4d4f030a-f60a-4bf9-aa47-9229c0e95622
@publicId = 4bbc7af5-ab60-48a6-b713-eba3b6e77cfd
@eventId = 908d82b0-bedd-4b04-8172-5200396cd92d

### CREATE EVENT
# @no-log
POST {{backend}}/event
Content-Type: application/json

{
  "localTime": "2025-01-01T12:00:00.000Z",
  "ip": "127.0.0.1",
  "data": { "page": "/home", "clicked": true },
  "actionId": "{{actionId}}"
}

###

### LIST EVENTS (current user)
# @no-log
GET {{backend}}/event
    ?pageNumber=1
    &perPage=5
    &orderBy=createdAt
    &sortOrder=DESC
    &actionId={{actionId}}
Content-Type: application/json

###

### GET EVENT BY ID
# @no-log
GET {{backend}}/event/{{eventId}}
Content-Type: application/json

###

### UPDATE EVENT
# @no-log
PATCH {{backend}}/event/{{eventId}}
Content-Type: application/json

{
  "ip": "192.168.1.10",
  "data": {
    "page": "/dashboard",
    "clicked": false
  }
}

###

### DELETE EVENT
# @no-log
DELETE {{backend}}/event/{{eventId}}
Content-Type: application/json

###

### PUBLIC EVENT
< {%
  const event = Date.now().toString(36);
  request.variables.set('event', event);
  const clicked = Boolean(Math.floor(Math.random() * 10));
  request.variables.set('clicked', clicked);
  const ip = `127.0.0.${Math.floor(Math.random() * 255)}`;
  request.variables.set('ip', ip);
  const localTime = new Date().toISOString();
  request.variables.set('localTime', localTime);
%}
POST {{backend}}/public
Content-Type: application/json

{
  "id": "{{publicId}}",
  "data": { "userEvent": "{{event}}", "clicked": {{clicked}} },
  "ip": "{{ip}}",
  "localTime": "{{localTime}}"
}

###
