### HEALTH

GRAPHQL {{graphql}}

{
    health
}

###

### SOURCES
GRAPHQL {{graphql}}

{
    sources(pagination: {pageNumber: 1, perPage: 1}) {
        total,
        results {
            id,
            actions {
                name,
                events {
                    ip,
                    localTime,
                    data
                }
            }
        }
    }
}

###

### SOURCE
GRAPHQL {{graphql}}

{
    source(id: "dfd5b1a0-8b90-4543-bace-b8fe02eb88a2") {
        id,
        title
    }
}

###

### ACTIONS
GRAPHQL {{graphql}}

{
    actions(pagination: {pageNumber: 1, perPage: 2}) {
        total,
        results {
            id,
            name,
            events {
                id,
                ip,
                localTime,
                createdAt
            }
        }
    }
}

###

### ACTION
GRAPHQL {{graphql}}

{
    action(id: "20e742ed-dabd-420a-943d-93820c4fedaf") {
        id,
        name,
        publicId
    }
}

###

### EVENTS
GRAPHQL {{graphql}}

{
    events {
        total,
        results {
            id,
            ip,
            localTime,
            createdAt
        }
    }
}

###

### EVENT
GRAPHQL {{graphql}}

{
    event(id: "06eec06a-6012-42ff-914c-680048a228ac") {
        id,
        ip,
        localTime,
        createdAt
    }
}

###
