@sourceId = d205acf3-acb0-46f8-972c-b68187653573

### CREATE SOURCE
# @no-log
POST {{backend}}/source
Content-Type: application/json

{
  "title": "DataHamster",
  "description": "datahamster.online"
}

###

### LIST SOURCES (current user)
# @no-log
GET {{backend}}/source
    ?pageNumber=1
    &perPage=100
    &orderBy=createdAt
    &sortOrder=ASC
Content-Type: application/json

###

### GET SOURCE BY ID
# @no-log
GET {{backend}}/source/{{sourceId}}
Content-Type: application/json

###

### UPDATE SOURCE
# @no-log
PATCH {{backend}}/source/{{sourceId}}
Content-Type: application/json

{
  "title": "Renamed Source",
  "description": "Updated description"
}

###

### DELETE SOURCE
# @no-log
DELETE {{backend}}/source/{{sourceId}}
Content-Type: application/json

###
